### PR TITLE
Fixing detection of 3 and 5 numpad keys

### LINKED ISSUE #6: Numpad keys 3 and 5 aren't detected.
**Steps to reproduce:**
 - Open the activity
 - Enter 3 using the numpad(NumLock on)

**Expected Result:**
 - 3 should come up in the input side

**Observer Result:**
No change

**Log:** 
`Key KP_Next unrecognised`
`Key KP_Begin unrecognised`
come up for Numpad 3 and 5 keystrokes

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Fixes https://github.com/sugarlabs/CowBulls-activity/issues/6

### CODE REVIEW

**Comment by rhl-bthr** [comment]
Thanks, reviewed.
Interesting that the `3` key points to either `Page Down` or `Next` depending on the system.

Please make this fix in https://www.github.com/sugarlabs/sugargame and copy the patch to this repository

**Comment by rhl-bthr** [comment]
Yet another change to sync across all activities using `sugargame` :disappointed:

**Comment by Aniket21mathur** [comment]
@pro-panda thanks for reviewing.

> and copy the patch to this repository

Merging of this pull request will not be enough?
Thanks!

**Comment by rhl-bthr** [comment]
No, in my opinion.
See https://github.com/sugarlabs/across-and-down-activity/pull/6#issuecomment-434510027

**Pull request closed without merging**
