### PR TITLE
update sugargame to v1.3

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by ayushnawal** [comment]
Tested.
looks good.
@quozl please review

**Comment by quozl** [comment]
Thanks, but given your other pull requests involving the Sugargame API, I'd prefer to see you fix them before I review any further changes.

**Comment by ayushnawal** [comment]
I reviewed and fixed them as you suggested, you can review these changes now

**Review by srevinsaju — APPROVED** [review]
@ayushnawal Great. Tested works perfectly on Sugar Fedora SOAS 31 other than occassional black screen which I recreated on master too. Thanks. addressed in #16

**Comment by quozl** [comment]
@srevinsaju, how do you recreate black screen?  I think the Activity class should not call `show_all`, as that would begin a race between GTK+ and Pygame initialisation.  The Sugargame test activity does not call it, and we saw black screen problems in some activities if it were called.

**Comment by ayushnawal** [comment]
> @srevinsaju, how do you recreate black screen?

There is a small wait (black screen) when the play button is pressed on the toolbar.

Fixes #16 now, @srevinsaju, please review :grin:

**Comment by srevinsaju** [comment]
@ayushnawal tested. Fundamentally the code is the same. Now, the black screen is no longer seen. The black screen was added to force redraw the screen contents. On play button press, now, the same content remains on the screen, (but actually it should redraw the entire screen). I have provided a clue in my review. Hope you will get a click and find the solution, alternatively, I shall tell what is to be done. Because, you might learn something more of sugargame if you fix this issue, which will help to solve 10+ open PRs which aims at almost the same issue.

Thanks

**Comment by srevinsaju** [comment]
> @srevinsaju, how do you recreate black screen? I think the Activity class should not call `show_all`, as that would begin a race between GTK+ and Pygame initialisation. The Sugargame test activity does not call it, and we saw black screen problems in some activities if it were called.

@quozl The black screen can be recreated on https://github.com/sugarlabs/CowBulls-activity/pull/15/commits/8a8a6acf99ac4e44587c10e4fd46d1d584132092 by pressing the play button and keeping the mouse on the toolbar and not moving it over the sugargame widget. This will make the black screen persistent. Once the cursor is moved over the sugargame widget, the black screen disappears, because the whole area is force - redrawn because of the mouse cursor

**Comment by ayushnawal** [comment]
@srevinsaju please review :grin: 

I have fixed the error that the same content remains on screen even after pressing the play button to restart, I have also fixed the same issue for the next round button.

Thanks

**Comment by ayushnawal** [comment]
@quozl @srevinsaju

**Comment by srevinsaju** [comment]
@ayushnawal Perfect. Tested https://github.com/sugarlabs/CowBulls-activity/pull/15/commits/dd3b8342a2751ee4528144953319666f64ffee57 . Works nice, no errors or warnings. Hope you are getting into groove with pygame and sugargame
Thanks, we will have a final review from @quozl before merge

**Comment by ayushnawal** [comment]
Thanks :grin: and yeah feeling more comfortable now

**Comment by quozl** [comment]
Thanks.  Tested and reviewed as at dd3b834.

* [ ] there's no explanation for the user how to play the game,
* [ ] the user interface elements in the canvas don't have any mouseover tooltips,
* [x] there are two play buttons in the toolbar; perhaps the "new game" button from other activities should be used in place of the first one,
* [ ] the winning smile is not centred,
* [ ] in hard level the number entry does not fit on my display (1024x768 pixels),
* [x] the CPU is heavily used redrawing the entire screen with no frame rate limitation; I suggest 15 to 25 frames per second should be adequate,
* [x] the Activity class should not call `show_all`, as in my experience this may cause a race condition depending on number of CPUs and system load,
* [x] the VIDEORESIZE event is only handled on the first call to the event loop function,
* [ ] the activity is not yet ported to Python 3, so can't be used,

**Comment by ayushnawal** [comment]
Thanks @quozl, reviewed back.

**Work in Progress**

>  the user interface elements in the canvas don't have any mouseover tooltips

elements such as buttons have mouseover tooltips, displaying on hovering the mouse as expected.

> there are two play buttons in the toolbar; perhaps the "new game" button from other activities should be used in place of the first one

Done as suggested, added `new-game.svg` , took it from `colordeducto`

> the winning smile is not centered

I found it perfect james, as it is not centered with respect to screen but at mid-point(centered) with respect to the output results and input field. Looking nice as it is now.

Screenshot from 2020-03-07 23-29-46

**Comment by ayushnawal** [comment]
>  the CPU is heavily used redrawing the entire screen with no frame rate limitation; I suggest 15 to 25 frames per second should be adequate.

Set fps to 20 as suggested.

> the Activity class should not call show_all

Done as suggested, called child widgets explicitly using `show` , working

> the VIDEORESIZE event is only handled on the first call to the event loop function,

Done, I guess this was only causing number entry not to fit in the hard level. looking nice on my system now.

Screenshot from 2020-03-08 15-16-02

>  there's no explanation for how to play the game.

Improved gameplay instructions.

Also improved readme.md in general

**Comment by quozl** [comment]
Thanks.  Tested as at 666fb3a.  Good progress.  Updated previous comment.

**Comment by ayushnawal** [comment]
>  there's no explanation for the user how to play the game

I am assuming that you want me to add a help button which on clicking displays you some basic rules/instructions, it is taking some time :sweat_smile:, but I am on it.

> there are two play buttons in the toolbar; perhaps the "new game" button from other activities should be used in place of the first one,

This is fixed here at [
160ecd7](https://github.com/sugarlabs/CowBulls-activity/pull/15/commits/160ecd7d6f6ee65d30575714e9ee81087ecc12d0)

> the user interface elements in the canvas don't have any mouseover tooltips
> the winning smile is not centred,

I reviewed and commented about these issues [here](https://github.com/sugarlabs/CowBulls-activity/pull/15#issuecomment-596127117)

> the activity is not yet ported to Python 3, so can't be used,

after all these fixes reviewed and approved, I can port the activity quickly.

**Comment by quozl** [comment]
Yes, a help button is one way.  An introduction screen is another way.  

I don't remember any mouseover tooltips for the buttons on the canvas.

**Comment by JuiP** [comment]
@quozl in [this](https://github.com/sugarlabs/CowBulls-activity/pull/15#issuecomment-592225471) comment, I think 

> - [ ]  the smile is not centered

should be ticked, as @ayushnawal mentioned before, it is not centered with respect to screen but at mid-point(centered) with respect to the output results and input field.

Also cherry-picked the commits in #17 also ported to python3

Edited - Correction, it does not center the smile for medium and hard levels. Shouldn't be ticked

**Comment by JuiP** [comment]
@quozl @chimosky with #17 merged, this PR can be closed.

**Comment by chimosky** [comment]
Thanks for noticing.

**Pull request closed without merging**
